from datetime import date
from app.models.story import UserStory


class MarkdownExporter:
    """Exports user stories as a professional Markdown backlog."""

    def export(
        self,
        stories: list[UserStory],
        source_files: list[str],
        ai_provider: str,
        project_name: str = "Architecture Analysis",
    ) -> str:
        lines = [
            f"# Product Backlog — {project_name}",
            "",
            f"_Generated by Archiscribe on {date.today().isoformat()}_",
            f"_Source files: {', '.join(source_files) or 'None'}_",
            f"_AI Provider: {ai_provider}_",
            "",
            "---",
            "",
        ]

        by_epic: dict[str, list[UserStory]] = {}
        for story in stories:
            by_epic.setdefault(story.epic, []).append(story)

        for epic_name, epic_stories in by_epic.items():
            lines.append(f"## Epic: {epic_name}")
            lines.append("")
            for story in epic_stories:
                lines.append(self._render_story(story))
                lines.append("")

        return "\n".join(lines)

    def _render_story(self, story: UserStory) -> str:
        lines = [
            f"### US-{story.id[:8].upper()}: {story.title}",
            "",
            f"**As a** {story.role}",
            f"**I want** {story.action}",
            f"**so that** {story.value}",
            "",
        ]

        if story.priority or story.story_points:
            meta = []
            if story.priority:
                meta.append(f"**Priority:** {story.priority}")
            if story.story_points:
                meta.append(f"**Story Points:** {story.story_points}")
            lines.append(" | ".join(meta))
            lines.append("")

        if story.acceptance_criteria:
            lines.append("#### Acceptance Criteria")
            for ac in story.acceptance_criteria:
                lines.append(f"- [ ] {ac.description}")
            lines.append("")

        if story.technical_notes:
            notes = story.technical_notes
            lines.append("#### Technical Notes")
            if notes.source_components:
                lines.append(f"- **Source components:** {', '.join(notes.source_components)}")
            if notes.source_flows:
                lines.append(f"- **Source flows:** {', '.join(notes.source_flows)}")
            if notes.diagram_references:
                lines.append(f"- **Diagram references:** {', '.join(notes.diagram_references)}")
            if notes.dependencies:
                lines.append(f"- **Dependencies:** {', '.join(notes.dependencies)}")
            lines.append("")

        lines.append("---")
        return "\n".join(lines)
